// Browser integration: node tests/creation-loadout.cjs
// Set BASE_URL to test a deployed copy; local default expects port 8765.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),...(process.env.BASE_URL&&process.env.HTTPS_PROXY?{proxy:{server:process.env.HTTPS_PROXY}}:{}),args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--no-zygote']});
 const sizes=process.env.SMOKE?[[390,844]]:[[320,568],[375,667],[390,844],[393,852],[430,932]];
 const base=process.env.BASE_URL||'http://localhost:8765';
 async function open(page){await page.goto(base);await page.locator('#splash').click();await page.locator('#splash').waitFor({state:'detached'})}
 const read=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('nehan_alpha_v1')));
 async function editor(page,kind){await page.locator(`[data-edit="${kind}"]`).click();assert(await page.locator('.creation-editor').isVisible())}
 async function geometry(page){const g=await page.evaluate(()=>{const a=document.querySelector('#app'),r=a.getBoundingClientRect(),rows=[...document.querySelectorAll('.creation-row')].map(e=>{const q=e.getBoundingClientRect();return {x:q.x,y:q.y,w:q.width,h:q.height}});return {rows,overflow:[document.documentElement.scrollWidth-innerWidth,document.documentElement.scrollHeight-innerHeight],bad:[...a.querySelectorAll('.creation-row,.creation-navigation button')].some(e=>{const q=e.getBoundingClientRect();return q.bottom>r.bottom+1||q.top<r.top-1||q.height<44||q.width<44}),buttons:document.querySelectorAll('.creation-row,.creation-navigation button').length}});assert.deepEqual(g.overflow,[0,0]);assert.equal(g.bad,false);assert.equal(g.buttons,6);g.rows.forEach(q=>{assert(Math.abs(q.x-g.rows[0].x)<1);assert(Math.abs(q.h-g.rows[0].h)<1);assert(Math.abs(q.w-g.rows[0].w)<1)})}
 for(const [width,height] of sizes){
  const page=await browser.newPage({viewport:{width,height},isMobile:true,hasTouch:true,ignoreHTTPSErrors:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>Math.random=()=>.5);await open(page);await page.locator('[data-nav="play"]').click();await page.locator('[data-new="0"]').click();await page.locator('.creation-background').evaluate(e=>e.decode());await page.evaluate(()=>document.fonts.ready);await geometry(page);
  assert(await page.locator('#createBtn').isDisabled());assert((await read(page)).slots.every(x=>x===null));
  await editor(page,'name');await page.locator('#nameInput').fill('電脳涅槃賞金稼ぎの名無し零壱弐参');assert.equal(await page.locator('#nameInput').getAttribute('maxlength'),'16');
  // Simulate the reduced visual viewport used while the software keyboard is up.
  await page.locator('#app').evaluate(e=>e.style.height='320px');assert(await page.locator('#confirmCreationEdit').isVisible());const keyboard=await page.locator('#confirmCreationEdit').boundingBox();assert(keyboard.y+keyboard.height<=320);
  await page.locator('#confirmCreationEdit').click();await page.locator('#app').evaluate(e=>e.style.height=innerHeight+'px');const name=(await read(page)).createDraft.name;assert.equal(name.length,16);assert.equal(await page.locator('[data-edit="name"] .creation-value').innerText(),name);assert((await read(page)).slots.every(x=>x===null));
  await editor(page,'job');assert((await page.locator('.creation-editor').innerText()).includes('VIT 6 / STR 8 / DEX 7 / INT 5'));assert((await page.locator('.creation-editor').innerText()).includes('武器習熟'));await page.locator('#confirmCreationEdit').click();
  await editor(page,'weapon');await page.locator('input[name="creationWeapon"]').check();assert((await page.locator('.creation-editor').innerText()).includes('命中 90% · STR · 1 HIT'));await page.locator('#confirmCreationEdit').click();assert(!(await page.locator('#createBtn').isDisabled()));
  await editor(page,'memory');await page.locator('[data-memory-slot="0"]').selectOption('M002');assert.equal(await page.locator('[data-memory-slot="1"]').inputValue(),'M001');await page.locator('#confirmCreationEdit').click();assert.deepEqual((await read(page)).createDraft.memoryIds,['M002','M001','M003','M004']);
  await editor(page,'name');await page.locator('#nameInput').fill('取り消し');await page.locator('#cancelCreationEdit').click();assert.equal((await read(page)).createDraft.name,name);
  await page.locator('#creationBack').click();await page.locator('[data-new="0"]').click();assert.equal((await read(page)).createDraft.name,name);assert.deepEqual((await read(page)).createDraft.memoryIds,['M002','M001','M003','M004']);await geometry(page);
  await page.locator('.creation-viewport').evaluate(e=>{e.style.paddingTop='47px';e.style.paddingBottom='34px'});await geometry(page);await page.screenshot({path:process.env.SCREENSHOT_DIR?`${process.env.SCREENSHOT_DIR}/creation-${width}.png`:`/tmp/nehan-creation-${width}.png`});
  await page.locator('#createBtn').click();let s=await read(page),c=s.slots[0];assert.equal(s.run.phase,'map');assert.equal(c.name,name);assert.equal(c.jobId,'JOB_BOUNTY_HUNTER');assert.deepEqual(c.stats,{VIT:6,STR:8,DEX:7,INT:5});assert.equal(c.hp,42);assert.equal(c.maxHp,42);assert.equal(c.weapon.id,'W001');assert.equal(c.weapon.mainStat,'STR');assert.equal(c.weapon.hitCount,1);assert.deepEqual(c.memories.map(x=>x.definitionId),['M002','M001','M003','M004']);assert(c.memories.every(x=>x.currentCT===0&&x.breakageRate===0&&!x.broken&&x.modules.length===0));assert.equal(s.createDraft,null);
  assert.equal(await page.locator('.action-name').first().innerText(),'鉄管ブレード');assert.equal(await page.locator('[data-memory="0"] + .action-name').innerText(),'速断');assert.equal(await page.locator('[data-memory="0"] img').getAttribute('src'),'assets/action-2.svg');
  await page.reload();await page.locator('#splash').click();await page.locator('#splash').waitFor({state:'detached'});await page.locator('[data-nav="play"]').click();assert((await page.locator('[data-slot="0"]').innerText()).includes('賞金稼ぎ'));await page.locator('[data-slot="0"]').click();assert.deepEqual((await read(page)).slots[0],c);
  await page.locator('[data-route="L"]').click();await page.locator('[data-memory="0"]').click();assert.equal((await read(page)).run.combat.enemy.hp,21);assert.equal(await page.locator('[data-memory="0"] .action-ct').innerText(),'1');await page.waitForTimeout(800);await page.locator('#weaponBtn').click();assert.equal((await read(page)).run.combat.enemy.hp,9);assert(await page.locator('.enemy-figure .damage-popup').isVisible());await page.waitForTimeout(1500);assert.equal((await read(page)).run.combat.enemy.turn,1);assert.equal((await read(page)).slots[0].hp,36);assert.deepEqual(errors,[]);console.log(`${width}×${height}: draft/edit/selection/keyboard-fit/safe-area/reload/map/combat PASS`);await page.close();
 }
 // Legacy fixtures preserve values, installed Modules and Memory state.
 const page=await browser.newPage({viewport:{width:390,height:844},ignoreHTTPSErrors:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>Math.random=()=>.5);
 const c={id:'legacy-body',name:'旧義体',stats:{VIT:10,STR:8,DEX:8,INT:8},maxHp:42,hp:29,weapon:{id:'W001',name:'鉄管ブレード',basePower:9,hit:90},memories:['M001','M002','M003','M004'].map((definitionId,i)=>({definitionId,currentCT:i===1?1:0,breakageRate:2,broken:false,modules:i===0?[{id:'legacy-module'}]:[]})),depth:3,wins:2,createdAt:1};
 const old={slots:[c,null,null],activeSlot:0,screen:'run',run:{ownerId:c.id,depth:2,phase:'map',shield:4,combat:null,routes:[{side:'L',enemyId:'E01',future:['違法義体狩り','逆接僧兵']},{side:'R',enemyId:'E02',future:['逆接僧兵','廃棄ドローン']}],log:[]}};
 await page.addInitScript(state=>{if(!localStorage.getItem('nehan_alpha_v1'))localStorage.setItem('nehan_alpha_v1',JSON.stringify(state))},old);await open(page);await page.locator('[data-nav="play"]').click();await page.locator('[data-slot="0"]').click();let s=await read(page);assert.equal(s.slots[0].jobId,'LEGACY');assert.equal(s.slots[0].weapon.mainStat,'STR');assert.equal(s.slots[0].weapon.hitCount,1);assert.equal(s.slots[0].hp,29);assert.deepEqual(s.slots[0].stats,c.stats);assert.deepEqual(s.slots[0].memories.map(({instanceId,rarity,moduleSlots,modules,...m})=>({...m,modules:modules.map(({instanceId,definitionId,rarity,generatedDepth,effectCount,effects,slotIndex,...mod})=>mod)})),c.memories);assert.equal(s.run.shield,4);
 await page.locator('[data-route="L"]').click();await page.locator('#weaponBtn').click();assert.equal((await read(page)).run.combat.enemy.hp,28);await page.waitForTimeout(1500);await page.locator('[data-memory="1"]').click();assert((await read(page)).run.combat.enemy.hp<28);await page.waitForTimeout(800);await page.locator('#exitRun').click();await page.locator('[data-nav="inventory"]').click();await page.locator('[data-nav="inventory"]').click();assert((await page.locator('.inventory-panel').innerText()).includes('破砕'));assert.deepEqual(errors,[]);console.log('Legacy save, weapon fallback, Memory use and Inventory PASS');
 // Exercise non-STR reference with an injected instance, without adding a production weapon.
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('nehan_alpha_v1'));s.slots[0].weapon.mainStat='DEX';s.slots[0].stats.DEX=0;s.run.combat.enemy.hp=100;s.run.combat.enemy.maxHp=100;localStorage.setItem('nehan_alpha_v1',JSON.stringify(s))});await page.reload();await page.locator('#splash').click();await page.locator('#splash').waitFor({state:'detached'});await page.locator('[data-nav="play"]').click();await page.locator('[data-slot="0"]').click();await page.locator('#weaponBtn').click();assert.equal((await read(page)).run.combat.enemy.hp,91);console.log('Weapon mainStat reference PASS');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
