const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{
const base=process.env.BASE_URL||'http://localhost:8765';
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-gpu','--no-zygote'],...(process.env.BASE_URL&&process.env.HTTPS_PROXY?{proxy:{server:process.env.HTTPS_PROXY}}:{})});
const read=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('nehan_alpha_v1')));
async function open(p){await p.goto(base);await p.locator('#splash').click();await p.locator('#splash').waitFor({state:'detached'});await p.locator('[data-nav="play"]').click();await p.locator('[data-slot="0"]').click()}
const p=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,ignoreHTTPSErrors:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));
const m=(id,instanceId,rarity='COMMON',modules=[])=>({instanceId,definitionId:id,rarity,moduleSlots:0,modules,currentCT:0,breakageRate:0,broken:false});
const fibre={instanceId:'fibre',definitionId:'MOD002'},circuit={instanceId:'stored-circuit',definitionId:'MOD001'};
const outgoing=m('M001','equipped-one','COMMON',[fibre]);outgoing.breakageRate=4.25;
const incoming=m('M002','stored-memory','RARE',[circuit]);incoming.currentCT=2;incoming.breakageRate=7.5;incoming.broken=true;
const c={id:'equipment-body',jobId:'JOB_BOUNTY_HUNTER',name:'賞金稼ぎ',stats:{VIT:6,STR:20,DEX:20,INT:5},maxHp:42,hp:35,weapon:{instanceId:'weapon-one',id:'W001',name:'鉄管ブレード',weaponType:'BLADE',mainStat:'STR',basePower:9,hit:90,hitCount:1,rarity:'COMMON',moduleSlots:0,modules:[]},memories:[outgoing,m('M002','equipped-two'),m('M003','equipped-three','LEGENDARY'),m('M004','equipped-four','UNCOMMON')],inventory:{memories:[incoming],modules:[{instanceId:'loose-one',definitionId:'MOD001'},{instanceId:'loose-two',definitionId:'MOD002'}]},depth:0,wins:0,createdAt:1};
const fixture={slots:[c,null,null],activeSlot:0,screen:'run',run:{ownerId:c.id,depth:0,phase:'map',shield:0,combat:null,routes:[{side:'L',enemyId:'E01',future:['廃棄ドローン','逆接僧兵']},{side:'R',enemyId:'E02',future:['違法義体狩り','逆接僧兵']}],log:[]}};
await p.addInitScript(f=>{Math.random=()=>.25;if(!localStorage.getItem('nehan_alpha_v1'))localStorage.setItem('nehan_alpha_v1',JSON.stringify(f))},fixture);await open(p);
assert.deepEqual((await read(p)).slots[0].memories.map(x=>x.moduleSlots),[1,1,5,2]);
await p.locator('#playerDetails').click();let manager=p.locator('.character-overlay');assert(await manager.isVisible());assert((await manager.innerText()).includes('HP 35 / 42'));assert.equal(await manager.locator('[data-equipment]').count(),5);
await manager.locator('[data-equipment="equipped-three"]').click();assert.equal(await manager.locator('.module-slot').count(),5);
for(const [width,height] of [[320,568],[375,667],[390,844],[393,852],[430,932]]){
 await p.setViewportSize({width,height});await p.waitForFunction(()=>Math.abs(document.querySelector('#app').getBoundingClientRect().height-innerHeight)<1);
 const g=await manager.evaluate(e=>{const r=e.querySelector('.install-card').getBoundingClientRect();return {r:{left:r.left,top:r.top,right:r.right,bottom:r.bottom},slots:[...e.querySelectorAll('.module-slot')].map(x=>{const b=x.getBoundingClientRect();return [b.width,b.height,b.right]}),overflow:[document.documentElement.scrollWidth-innerWidth,document.documentElement.scrollHeight-innerHeight]}});
 assert.deepEqual(g.overflow,[0,0]);assert(g.r.left>=0&&g.r.top>=0&&g.r.right<=width+1&&g.r.bottom<=height+1);assert(g.slots.every(([w,h,right])=>w>=44&&h>=44&&right<=width));
}
await p.setViewportSize({width:390,height:844});await manager.locator('#equipmentOverview').click();await manager.locator('[data-equipment="weapon-one"]').click();assert((await manager.innerText()).includes('HIT COUNT 1'));
async function chooseCircuit(){await manager.locator('[data-empty-module-slot]').click();await p.locator('[data-pick-module="loose-one"]').click();assert((await p.locator('.module-install-overlay').innerText()).includes('取り外せません'));}
await chooseCircuit();await p.locator('#cancelInstall').click();assert.equal((await read(p)).slots[0].weapon.modules.length,0);
await chooseCircuit();await p.locator('#confirmInstall').click();assert.equal(await manager.locator('.occupied').count(),1);assert.equal(await manager.locator('[data-empty-module-slot]').count(),0);assert.equal((await read(p)).slots[0].weapon.modules[0].instanceId,'loose-one');
await manager.locator('#equipmentOverview').click();assert((await manager.innerText()).includes('STR 20 → 28'));assert((await manager.innerText()).includes('DEX 20 → 14'));
await manager.locator('[data-equipment="equipped-one"]').click();await manager.locator('#changeMemory').click();await p.locator('[data-swap-memory="stored-memory"]').click();
let s=await read(p);assert.equal(s.slots[0].memories[0].instanceId,'stored-memory');assert.deepEqual(s.slots[0].memories[0].modules,[circuit]);assert.equal(s.slots[0].memories[0].currentCT,2);assert.equal(s.slots[0].memories[0].breakageRate,7.5);assert(s.slots[0].memories[0].broken);assert.equal(s.slots[0].inventory.memories[0].instanceId,'equipped-one');assert.deepEqual(s.slots[0].inventory.memories[0].modules,[fibre]);assert.equal(s.slots[0].inventory.memories[0].breakageRate,4.25);assert.deepEqual(s.slots[0].stats,c.stats);
assert((await manager.innerText()).includes('BROKEN'));assert.equal(await manager.locator('.module-slot').count(),3);assert.equal(await manager.locator('[data-empty-module-slot]').count(),2);
if(process.env.SCREENSHOT_DIR)await p.screenshot({path:`${process.env.SCREENSHOT_DIR}/equipment-memory.png`});
await manager.locator('#equipmentOverview').click();assert((await manager.innerText()).includes('STR 20 → 24'));assert((await manager.innerText()).includes('DEX 20 → 10'));await manager.locator('.equipment-dialog-close').click();assert.equal(await manager.count(),0);assert.equal(await p.locator('[data-memory="0"] img').getAttribute('src'),'assets/action-2.svg');
await p.reload();await p.locator('#splash').click();await p.locator('#splash').waitFor({state:'detached'});await p.locator('[data-nav="play"]').click();await p.locator('[data-slot="0"]').click();assert.equal((await read(p)).slots[0].memories[0].instanceId,'stored-memory');
await p.locator('[data-route="L"]').click();await p.locator('#playerDetails').click();manager=p.locator('.character-overlay');assert((await manager.innerText()).includes('詳細確認のみ'));await manager.locator('[data-equipment="stored-memory"]').click();assert(await manager.locator('#changeMemory').isDisabled());assert(await manager.locator('[data-empty-module-slot]').first().isDisabled());const unchanged=await read(p);await manager.locator('.equipment-dialog-close').click();assert.deepEqual((await read(p)).slots[0],unchanged.slots[0]);
// The Home Inventory cannot bypass the guard on an active combat character.
await p.locator('#exitRun').click();await p.locator('[data-nav="inventory"]').click();await p.locator('[data-nav="inventory"]').click();await p.locator('[data-inventory-tab="modules"]').click();assert(await p.locator('[data-install-module="loose-two"]').isDisabled());await p.locator('[data-inventory-tab="equipped"]').click();await p.locator('[data-equipment="stored-memory"]').click();assert(await p.locator('.character-overlay #changeMemory').isDisabled());await p.locator('.character-overlay .equipment-dialog-close').click();
// Reading details while an action is pending leaves the original timing alive.
await p.locator('[data-nav="home"]').click();await p.locator('[data-nav="play"]').click();if(await p.locator('#app[data-screen="home"]').count())await p.locator('[data-nav="play"]').click();await p.locator('[data-slot="0"]').click();await p.locator('#weaponBtn').click();await p.locator('#playerDetails').click();await p.waitForTimeout(1600);s=await read(p);assert.equal(s.run.combat.enemy.turn,1);assert.equal(s.slots[0].hp,29);assert(await p.locator('.character-overlay').isVisible());await p.locator('.character-overlay .equipment-dialog-close').click();assert((await p.locator('#playerDetails').innerText()).includes('29 / 42'));
assert.deepEqual(errors,[]);console.log('5 mobile sizes, map/combat/Home entry, permanent install/cancel, complete Memory swap/save/effective stats, combat guards and pending timers PASS');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
