const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const code=fs.readFileSync('index.html','utf8').split('<script>')[1].split('</script>')[0].split('state.screen="home";\nrender();')[0].replace('(() => {',''),storage=new Map();
const context=vm.createContext({console,crypto:require('node:crypto').webcrypto,document:{querySelector:()=>({})},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout,clearTimeout});vm.runInContext(code,context);vm.runInContext(`render=()=>{};
function lcg(seed){return ()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);}
function fixture(){const c=createCharacter({name:"探索",jobId:"JOB_BOUNTY_HUNTER",weaponId:"W001",memoryIds:["M001","M002","M003","M004"]});state={...freshState(),slots:[c,null,null],activeSlot:0,screen:"run",run:{...newRun(c),ownerId:c.id}};return c;}
function routes(type){return [{id:itemId(),side:"L",type,...(type==="battle"?{enemyId:"E01"}:{}),future:[{id:"next-garage",type:"garage"},{id:"next-scrap",type:"scrap"}]},{id:itemId(),side:"R",type:"battle",enemyId:"E02",future:[]}];}
let c=fixture();`,context);const run=s=>JSON.parse(vm.runInContext(`JSON.stringify(${s})`,context));
const counts=run(`(()=>{const rng=lcg(32),current={battle:0,garage:0,scrap:0},future={battle:0,garage:0,scrap:0};for(let i=0;i<20000;i++){for(const route of makeRoutes(i%40,rng)){current[route.type]++;for(const n of route.future)future[n.type]++;}}return {current,future};})()`);
for(const [kind,p] of Object.entries({battle:.6,garage:.2,scrap:.2})){assert(Math.abs(counts.current[kind]/40000-p)<.01);assert(Math.abs(counts.future[kind]/80000-p)<.01);}console.log('MAP current/future distributions',counts);
const rarity=run(`(()=>{return [1,10,20,30,50,10000].map(depth=>{const rng=lcg(10),counts={COMMON:0,UNCOMMON:0,RARE:0,EPIC:0,LEGENDARY:0};for(let i=0;i<20000;i++)counts[rollItemRarity(depth,rng)]++;return {depth,counts,average:Object.entries(counts).reduce((n,[k,v])=>n+(Object.keys(RARITY_SLOTS).indexOf(k)+1)*v,0)/20000};});})()`);for(let i=1;i<5;i++)assert(rarity[i].average>rarity[i-1].average);assert.equal(rarity[4].average,rarity[5].average);assert(rarity[0].counts.LEGENDARY>0);assert(rarity[4].counts.COMMON>0);console.log('Scrap rarity metrics',rarity);
const scrapCounts=run(`(()=>{const rng=lcg(12),counts={WEAPON:0,MEMORY:0};for(let i=0;i<20000;i++){const loot=generateScrapLoot(i%50,rng);counts[loot.type]++;if(loot.item.moduleSlots!==RARITY_SLOTS[loot.item.rarity]||!loot.item.instanceId||loot.item.modules.length)throw Error("instance/slots");}return counts;})()`);assert(Math.abs(scrapCounts.WEAPON/20000-.5)<.01);console.log('Scrap split',scrapCounts);
vm.runInContext(`c.hp=12;c.weapon.modules=[{instanceId:"max-hp",definitionId:"MOD001",slotIndex:0,effects:[{target:"MAX_HP",mode:"flat",value:18}]}];c.memories[0].currentCT=2;c.memories[0].breakageRate=7.5;c.memories[0].broken=true;const memorySnapshot=JSON.stringify(c.memories);state.run.routes=routes("garage");`,context);assert(run('handleMapNode("L")'));assert.equal(run('state.run.phase'),'garage');assert.equal(run('state.run.depth'),0);assert(!run('handleMapNode("L")'));vm.runInContext('save();state=load();c=state.slots[0];',context);assert(run('completeGarage(c)'));assert.equal(run('c.hp'),60);assert.equal(run('c.maxHp'),42);assert(run('JSON.stringify(c.memories)===memorySnapshot'));assert.equal(run('state.run.depth'),1);assert.equal(run('c.depth'),1);assert.equal(run('c.wins'),0);assert.deepEqual(run('state.run.routes.map(r=>r.type)'),['garage','scrap']);assert.deepEqual(run('state.run.routes.map(r=>r.id)'),['next-garage','next-scrap']);assert(!run('completeGarage(c)'));assert.equal(run('state.run.depth'),1);
vm.runInContext('c.hp=15;state.run.routes=routes("garage");',context);assert(run('handleMapNode("L")'));assert(run('completeGarage(c,false)'));assert.equal(run('c.hp'),15);assert.equal(run('state.run.depth'),2);
for(const [type,roll,bag] of [['WEAPON',.1,'weapons'],['MEMORY',.8,'memories']]){
 vm.runInContext(`c=fixture();c.inventory.modules=[{instanceId:"untouched",definitionId:"MOD001",effects:[]}];state.run.depth=12;state.run.routes=routes("scrap");Math.random=()=>${roll};var equipped=JSON.stringify({weapon:c.weapon,memories:c.memories});`,context);assert(run('handleMapNode("L")'));assert.equal(run('state.run.phase'),'scrap');assert.equal(run('state.run.depth'),12);const loot=run('state.run.scrapLoot');assert.equal(loot.type,type);assert(!run('handleMapNode("L")'));vm.runInContext('save();Math.random=()=>.999;state=load();c=state.slots[0];',context);assert.deepEqual(run('state.run.scrapLoot'),loot);assert(run('collectScrap(c)'));assert.equal(run(`c.inventory.${bag}.length`),1);assert.deepEqual(run(`c.inventory.${bag}[0]`),loot.item);assert.equal(run('c.inventory.modules.length'),1);assert(run('JSON.stringify({weapon:c.weapon,memories:c.memories})===equipped'));assert.equal(run('state.run.depth'),13);assert(!run('collectScrap(c)'));assert.equal(run('state.run.depth'),13);
}
vm.runInContext('c=fixture();state.run.routes=routes("battle");Math.random=()=>.1;',context);assert(run('handleMapNode("L")'));assert.equal(run('state.run.phase'),'combat');assert(!run('startCombat("L")'));vm.runInContext('state.run.combat.enemy.hp=0;',context);assert(run('checkVictory(c)'));assert.equal(run('state.run.depth'),0);assert.equal(run('c.wins'),1);assert.equal(run('state.run.phase'),'loot');assert(!run('checkVictory(c)'));vm.runInContext('save();state=load();c=state.slots[0];',context);assert.equal(run('state.run.lootDepthAdvanced'),false);assert(run('collectLoot(c)'));assert.equal(run('state.run.depth'),1);assert(!run('collectLoot(c)'));assert.equal(run('state.run.depth'),1);
// Packed old routes, string previews, missing weapon storage and old already-advanced loot.
const legacy=run(`(()=>{const s=JSON.parse(JSON.stringify(state));delete s.slots[0].inventory.weapons;s.run={ownerId:s.slots[0].id,phase:"loot",depth:7,loot:{type:"MEMORY",item:createMemoryInstance("M002")},routes:[{side:"L",enemyId:"E01",future:["逆接僧兵","違法義体狩り"]}]};return normalizeState(s);})()`);assert.deepEqual(legacy.slots[0].inventory.weapons,[]);assert.equal(legacy.run.routes[0].type,'battle');assert.deepEqual(legacy.run.routes[0].future.map(n=>n.enemyId),['E03','E02']);assert(legacy.run.lootDepthAdvanced);vm.runInContext(`state=${JSON.stringify(legacy)};c=state.slots[0];`,context);assert(run('collectLoot(c)'));assert.equal(run('state.run.depth'),7);assert(!run('collectLoot(c)'));assert.equal(run('state.run.depth'),7);
// Stored weapons are usable installation targets but cannot modify an equipped character.
vm.runInContext(`const w=createWeaponInstance("W001","RARE");c.inventory.weapons.push(w);const mod={instanceId:itemId(),definitionId:"MOD001",effects:[{target:"STR",mode:"flat",value:100}]};c.inventory.modules.push(mod);const before=getEffectiveStats(c).STR;`,context);assert(run('installModule(c,mod.instanceId,w.instanceId,2)'));assert.equal(run('getEffectiveStats(c).STR'),run('before'));assert.equal(run('w.moduleSlots'),3);assert.equal(run('w.modules[0].slotIndex'),2);
console.log('All 18 node requirements: dispatch, preview continuity, heal/leave, unchanged CT/broken, no reroll/reuse, instance storage, depth once, weighted quality and legacy pending loot PASS');
