const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('index.html','utf8'),code=source.split('<script>')[1].split('</script>')[0].split('state.screen="home";\nrender();')[0].replace('(() => {','');
const store=new Map(),ctx=vm.createContext({console,crypto:require('node:crypto').webcrypto,document:{querySelector:()=>({})},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},setTimeout:()=>0,clearTimeout:()=>{}});vm.runInContext(code,ctx);
const exec=s=>vm.runInContext(s,ctx),read=s=>JSON.parse(exec(`JSON.stringify(${s})`));
exec(`render=()=>{};scheduleCombatResolution=()=>{};state=freshState();function draft(){return {name:'次の義体',jobId:'JOB_BOUNTY_HUNTER',weaponId:'W001',memoryIds:['M001','M002','M003','M004']};}function die(c){state.slots[0]=c;state.activeSlot=0;state.run=newRun(c);state.run.ownerId=c.id;state.run.phase='dead';c.hp=0;}function allOwned(){return [...state.metaInventory.memories,...state.slots.filter(Boolean).flatMap(c=>[...c.memories,...c.inventory.memories])];}let c=createCharacter(draft());die(c);let item=c.memories[0];item.rarity='RARE';item.moduleSlots=3;item.breakageRate=63.48;item.currentCT=4;item.generatedDepth=18;item.extra={custom:'preserve'};item.modules=[{instanceId:'installed',definitionId:'MOD001',slotIndex:1,effects:[{target:'STR',mode:'percent',value:15}]}];item.modules.forEach(normalizeModule);let original=JSON.stringify({...item,currentCT:0});let instanceId=item.instanceId;`);
assert.equal(read('completeMemorySalvage(c,instanceId)'),true);assert.equal(read('state.slots[0]'),null);assert.equal(read('state.run'),null);assert.equal(read('state.metaInventory.memories[0].breakageRate'),63.48);assert(read('state.metaInventory.memories[0]===item'));assert.equal(read('JSON.stringify(item)'),read('original'));assert.equal(read('item.currentCT'),0);
exec('save();state=load();item=state.metaInventory.memories[0];');assert.equal(read('JSON.stringify(item)'),read('original'));
exec(`let d=draft();setCreationMemory(d,0,'recovered:'+instanceId);state.createDraft=d;save();`);assert.equal(read('state.metaInventory.memories.length'),1);assert.equal(read('state.slots.filter(Boolean).length'),0);assert(read('validCreationDraft(d)'));
// Cancelling an editor or returning to PLAY never transfers an object.
exec(`let cancelled={...d,memoryIds:[...d.memoryIds],recoveredMemoryIds:[...d.recoveredMemoryIds]};setCreationMemory(cancelled,0,'M001');state.screen='play';save();state=load();d=state.createDraft;item=state.metaInventory.memories[0];`);assert.equal(read('state.metaInventory.memories.length'),1);assert.equal(read('d.recoveredMemoryIds[0]'),read('instanceId'));
exec(`let invalid={...d,weaponId:null};let rejected=false;try{createCharacter(invalid);}catch{rejected=true;}`);assert(read('rejected'));assert.equal(read('state.metaInventory.memories.length'),1);
exec('c=createCharacter(d);state.slots[0]=c;state.createDraft=null;state.run=newRun(c);state.run.ownerId=c.id;');assert.equal(read('state.metaInventory.memories.length'),0);assert(read('c.memories[0]===item'));assert.equal(read('c.memories[0].instanceId'),read('instanceId'));assert.equal(read('JSON.stringify(c.memories[0])'),read('original'));assert.equal(read('new Set(allOwned().map(m=>m.instanceId)).size'),read('allOwned().length'));assert.equal(read('validCreationDraft(d)'),false);
exec(`state.run.phase='combat';state.run.combat={enemy:{name:'敵',hp:1000,guard:0},playerBuffs:[],log:[]};Math.random=()=>.5;useMemory(c,0);`);assert.equal(read('c.memories[0].breakageRate'),64.98);assert.equal(read('c.memories[0].modules[0].instanceId'),'installed');
exec(`save();state=load();c=state.slots[0];item=c.memories[0];let savedItem=JSON.stringify({...item,currentCT:0});die(c);`);assert.equal(read('state.metaInventory.memories.length'),0);assert(read('salvageCandidates(c).includes(item)'));assert(read('completeMemorySalvage(c,item.instanceId)'));assert.equal(read('JSON.stringify(state.metaInventory.memories[0])'),read('savedItem'));
exec(`d=draft();setCreationMemory(d,0,'recovered:'+instanceId);c=createCharacter(d);die(c);completeMemorySalvage(c);`);assert.equal(read('allOwned().some(m=>m.instanceId===instanceId)'),false);
// Broken instances and storage memories are eligible and are never repaired.
exec(`c=createCharacter(draft());let broken=createMemoryInstance('M005');broken.breakageRate=100;broken.broken=true;broken.currentCT=5;c.inventory.memories.push(broken);die(c);completeMemorySalvage(c,broken.instanceId);d=draft();setCreationMemory(d,0,'recovered:'+broken.instanceId);c=createCharacter(d);state.slots[0]=c;state.run=newRun(c);state.run.ownerId=c.id;`);assert.equal(read('c.memories[0].breakageRate'),100);assert.equal(read('c.memories[0].broken'),true);assert.equal(read('c.memories[0].currentCT'),0);assert(read('c.memories[0]===broken'));
exec(`save();state=load();c=state.slots[0];state.run.phase='combat';state.run.combat={enemy:{hp:100},playerBuffs:[],log:[]};let before=JSON.stringify(c.memories[0]);useMemory(c,0);`);assert.equal(read('JSON.stringify(c.memories[0])'),read('before'));assert.equal(read('state.metaInventory.memories.length'),0);
// Legacy storage migration and accidental duplicated recovered references cannot clone live ownership.
exec(`let legacy=JSON.parse(JSON.stringify(state));delete legacy.metaInventory;state=normalizeState(legacy);`);assert.deepEqual(read('state.metaInventory'),{memories:[]});exec(`state.metaInventory.memories.push(state.slots[0].memories[0]);state=normalizeState(JSON.parse(JSON.stringify(state)));`);assert.equal(read('state.metaInventory.memories.length'),0);
exec(`state=freshState();let x=createMemoryInstance('M007');state.metaInventory.memories=[x,x];state=normalizeState(JSON.parse(JSON.stringify(state)));`);assert.equal(read('state.metaInventory.memories.length'),1);
console.log('14 salvage requirements PASS: exact instance/module/wear preservation, CT only reset, draft/cancel, consume-on-create, single ownership, normal wear, repeat salvage, skip loss, BROKEN, reload and legacy migration');
